In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('errors.csv')
df = df.groupby(['wrong_errotype', ' correct_errortype']).size()
new_df = df.to_frame(name = 'count').reset_index()
new_df = new_df[new_df['count'] > 10]
new_new_df = new_df.groupby(['wrong_errotype', ' correct_errortype']).sum().unstack(fill_value=0)

In [7]:
new_new_df

                   count                                                      \
 correct_errortype   AGA AGN  AS  CN  DJ  DN  DV  DY  FD  FN  FV  IV   R  RV
wrong_errotype
AGN                    0   0   0   0   0   0   0   0   0  28   0   0   0   0
FN                     0  46   0  17   0   0   0   0   0   0   0   0   0   0
FV                     0   0   0   0   0   0   0   0   0   0   0   0   0   0
RA                    11   0   0   0   0   0   0   0   0   0   0   0  12   0
RD                     0   0   0   0   0   0   0   0  11   0   0   0  13   0
RJ                     0   0   0   0  24   0   0   0   0   0   0   0   0   0
RN                     0   0   0   0   0  42   0   0   0   0   0   0   0   0
RT                     0   0   0   0   0   0   0   0   0   0   0   0  15   0
RV                     0   0   0   0   0   0  11   0   0   0  12  31  11   0
RY                     0   0   0   0   0   0   0  18   0   0   0   0  11   0
TV                     0   0   0   0   0   0   0   0   0   0   0   0   0  44
UT                     0   0   0   0   0   0   0   0   0   0   0   0  15   0
W                      0   0  12   0   0   0   0   0   0   0   0   0  13   0


 correct_errortype  TV  UV
wrong_errotype
AGN                  0   0
FN                   0   0
FV                  14   0
RA                   0   0
RD                   0   0
RJ                   0   0
RN                   0   0
RT                   0   0
RV                  32  12
RY                   0   0
TV                   0   0
UT                   0   0
W                    0   0